version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: 'udayacademy_db'
      POSTGRES_USER: 'uday_user'
      POSTGRES_PASSWORD: '@!314dD@'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  web:
    build: .
    command: >
      sh -c "python manage.py migrate && gunicorn --workers 3 --bind 0.0.0.0:8000 myproject.wsgi:application"
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data: