apiVersion: v1
kind: PersistentVolume
metadata:
  name: clients-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/clients"  # Caminho no nó onde os dados serão armazenados

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: images-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/images"  # Caminho no nó onde os dados serão armazenados

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres"  # Caminho no nó onde os dados serão armazenados

